const express=require('express')
const cors = require('cors')
require('./dbConnetction/db')
const userRoutes = require('./routes/user.routes')
const taskRoutes = require('./routes/task.routes')
const app = express()
app.use(cors())
app.use(express.json())
app.use(userRoutes)
app.use(taskRoutes)
module.exports = app